#Connect to DB
spring:
  jpa:
    database: your data
    database-platform: your data
    show-sql: true/false
    open-in-view: true/false
    properties:
      hibernate:
        format_sql: true/false
#Hibernate Configuration:
  datasource:
    username: your username
    password: your password
    url: your url
    driver-class-name: driver for DB
