#Connect to DB
spring:
  jpa:
    database: 
    database-platform: 
    show-sql: 
    open-in-view: 
    properties:
      hibernate:
        format_sql: 
#Hibernate Configuration:
  datasource:
    username: 
    password:
    url: 
    driver-class-name: 
